### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by lemanno** [ky4910/KyMusicPlayer#1]
error: resource drawable/play_fragment_pause_selector (aka com.example.kimberjin.kymusicplayer:drawable/play_fragment_pause_selector) not found.

**Comment by ky4910** [comment]
For commit 987ab08
Add play_fragment_pause_selector.xml and play_fragment_play_selector.xml under the drawable directory. Add the selector in xml file and add item from drawable or mipmap icon.

**Comment by ky4910** [comment]
Caused by the lack of xml file.
